name: Experimental images

on:
  # Rebuild every quarter on Sunday at 8:20 UTC
  schedule:
    - cron: "20 8 * 1/3 0"

  # Build on push to main
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-experimental.yaml
      - "*.dockerfile"
      - files/**

  # Allow manually triggered rebuilds
  workflow_dispatch:

concurrency:
  group: build-experimental-images
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

# Run the automated tests first, then publish the images if the tests pass
jobs:
  test:
    name: ${{ matrix.dockerfile }}
    uses: ./.github/workflows/test-job.yaml
    with:
      dockerfile: ${{ matrix.dockerfile }}
    strategy:
      fail-fast: true
      matrix:
        dockerfile:
          - nginx

  nginx:
    name: Nginx
    needs: test
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: nginx.dockerfile
      image-version: experimental
      assert-version: false
      tags: |
        ghcr.io/${{ github.repository_owner }}/baikal:experimental
    secrets: inherit
