# Build a testing image from the testing branch (pre-release / WIP).
name: Testing images

on:
  push:
    branches:
      - testing

  workflow_dispatch:

concurrency:
  group: build-testing-images
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  test:
    name: ${{ matrix.dockerfile }}
    uses: ./.github/workflows/test-job.yaml
    with:
      dockerfile: ${{ matrix.dockerfile }}
    strategy:
      fail-fast: true
      matrix:
        dockerfile:
          - nginx

  nginx:
    name: Nginx
    needs: test
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: nginx.dockerfile
      image-version: testing
      assert-version: false
      tags: |
        ghcr.io/${{ github.repository_owner }}/baikal:testing
    secrets: inherit
